### ISSUE TITLE
spree_bootstrap_theme  did not have a valid gemspec.

### ISSUE THREAD

**Issue by nunziofiore** [andrewmp1/spree_bootstrap_theme#2]
I just report you an alert during installation, may be can help you fixing spec

Using spree_bootstrap_theme (0.1.0) from git://github.com/Andrewmp1/spree_bootstrap_theme.git (at master) 
spree_bootstrap_theme at /Users/nunzio/.rvm/gems/ruby-1.9.2-p290/bundler/gems/spree_bootstrap_theme-a8e7f5acfc9b did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  "FIXME" or "TODO" is not a description

**Comment by andrewmp1** [comment]
Thanks for the pull request.  I just merged it.
