### ISSUE TITLE
Product unclickable

### ISSUE THREAD

**Issue by nunziofiore** [andrewmp1/spree_bootstrap_theme#4]
Hi
if I make inspect of my catalog page I have something like this:

&lt;li class="products-list-item span2 selected" itemtype="http://schema.org/Product" itemscope="" data-hook="products_list_item" id="product_569012001"&gt;
        &lt;div class="product-image"&gt;
          &lt;a href="/products/ruby-baseball-jersey"&gt;&lt;img src="/spree/products/1008/small/ruby_baseball.png?1333385186" itemprop="name" alt="Ruby Baseball Jersey"&gt;&lt;/a&gt;
        &lt;/div&gt;
        &lt;a title="Ruby Baseball Jersey" itemprop="name" class="info" href="/products/ruby-baseball-jersey"&gt;Ruby Baseball Jersey&lt;/a&gt;
        &lt;span itemprop="price" class="price selling"&gt;$19.99&lt;/span&gt;
      &lt;/li&gt;

So the HTML it seems correct. But every "a" tag is unclickable.

I noticed if I remove core js from application.js , that the link became clickable. So in my opinion there's something wrong in the catalog template in your theme that prevent default click action. 
I try to investigate the error, in the meanwhile I just wrote you in case you have yet the solution.
Nunzio

**Comment by andrewmp1** [comment]
Thanks for submitting the issue.  I see the problem.  I'll take a look and see if I can't push a fix real quick.
