### ISSUE TITLE
Broken style

### ISSUE THREAD

**Issue by itsNikolay** [andrewmp1/spree_bootstrap_theme#5]
I set up twitter bootstrap gem and get broken style.
http://imageshack.us/photo/my-images/171/68012363.jpg/
Please help.

**Comment by leonardoafpinto** [comment]
That is happening with me too. Have you fixxed that yet?

**Comment by andrewmp1** [comment]
I haven't spent time on this gem in a while.  I apologize about that.  I'll try and take a look at this later today.  Any thoughts on a fix for this?  If you submit a pull request for a fix I'll definitely merge it

**Comment by umuthan** [comment]
did you run rake commands ?

rake assets:clean
rake assets:precompile

**Comment by leonardoafpinto** [comment]
Yes, i ran rake commands, but not happened.
I will take a look later too.

Are you using spree gem bundle in a project?

**Comment by leonardoafpinto** [comment]
Hey guys, i solve my problem running rake command "rake deface:precompile" wich precompiles overrides into template files.

Thanks

**Comment by itsNikolay** [comment]
After 9 month we solve it =) Thanks!

**Comment by leonardoafpinto** [comment]
Customize views with rake deface:precompile doesn't work for spree_bootstrap_theme.

Is there a way to customize the deface files of spree_bootstrap_theme?
