### ISSUE TITLE
Shared/login_bar Style Break

### ISSUE THREAD

**Issue by BrockFredin** [andrewmp1/spree_bootstrap_theme#6]
System:

Ubuntu Linux Maverick 
Rails 3.2.6
Spree Edge Source/Spree Bootstrap as of today's date

Issue:

This tag no longer references an existing login_bar available in Spree.  This breaks any styling for current Spree installs.  

<ul id="main-nav-bar" class="nav pull-right" data-hook>
          <%= render :partial => 'spree/shared/login_bar' %>

IN:

spree_bootstrap_theme / app / views / spree / overrides / _replace_body.html.erb

Actual

This error is raised when site is hit with a request:   ActionView::MissingTemplate in Spree/home#index

Showing /home/USER/Desktop/spree/core/app/views/spree/layouts/spree_application.html.erb where line #30 raised:

Missing partial spree/shared/login_bar with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :coffee, :rabl]}. Searched in:

Solution:

Needs to reference likely this shared view:  spree / shared / _main_nav_bar.html.erb OR  _nav_bar.html.erb OR _header.html.erb

**Comment by andrewmp1** [comment]
Thanks for posting this w/ the detail of the error & fix.  Just pushed a fix to this.  If you are using this in your project feel free to give me any more suggestions for this.  It's still pretty alpha.

**Comment by BrockFredin** [comment]
I was going to push the fix to you but installed it from my fork earlier
this morning.

The new spree has significant change and your theme needs major rework to
operate.

On Thu, Jun 28, 2012 at 1:54 PM, Drew <
reply@reply.github.com

> wrote:
> 
> Thanks for posting this w/ the detail of the error & fix.  Just pushed a
> fix to this.  If you are using this in your project feel free to give me
> any more suggestions for this.  It's still pretty alpha.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/Andrewmp1/spree_bootstrap_theme/issues/6#issuecomment-6638358

## 

_Brock Fredin_
*612-424-5512

*
