### ISSUE TITLE
Bootstrap-Image-Gallery somebody tried?

### ISSUE THREAD

**Issue by itsNikolay** [andrewmp1/spree_bootstrap_theme#8]
I tryed to set up https://github.com/blueimp/Bootstrap-Image-Gallery on spree_bootstrap_theme.
In devepment mode all work fine. But in production igetting error.
Uncaught TypeError: undefined is not a function  in line             this._loadingImage = loadImage(
http://vk-magazin.com/products/krossovki-adidas-1 (click on _thumbnails photos) and error appears.
Please if some body set it up on production please write.

**Comment by veevickytoria** [comment]
This may be too late for you, but I came across this post while searching for the same problem myself, so I thought it might help to answer this for future record:
All you need to do is change loadImage to window.loadImage

**Comment by itsNikolay** [comment]
Yes, it's a little late, but thanks anyway for your investigation. :yum: :

**Comment by Loremaster** [comment]
Thank you so much for your solution! It really helped mе a lot!
